version: '3.9'
services:
  db:
    image: postgres:15-alpine
    container_name: chat_postgres
    environment:
      POSTGRES_USER: gen_user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: default_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
      build: .
      container_name: chat_backend
      environment:
          DATABASE_URL: "postgresql+asyncpg://gen_user:password@1.1.1.1:5432/default_db"
          JWT_SECRET: "SUPER_SECRET_JWT_KEY"
      ports:
          - "8000:8000"

volumes:
  postgres_data:
